In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
type(x[1,1])

torch.Tensor

In [6]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [7]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x.view(2,5)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x.reshape(2,5)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x = x.view(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
x = torch.arange(10)
x.shape
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

In [26]:
a

tensor([1., 2., 3.])

In [27]:
a.dtype

torch.float32

In [28]:
a + b

tensor([5., 7., 9.])

In [29]:
torch.add(a, b)

tensor([5., 7., 9.])

In [33]:
a.mul_(b)
# a = a + b
a

tensor([ 4., 10., 18.])

In [34]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

In [36]:
a.dot(b)

tensor(32.)

In [37]:
a = torch.tensor([[0,2,4], [1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [38]:
b = torch.tensor([[6,7], [8,9], [10, 11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [39]:
torch.mm(a, b)

tensor([[56, 62],
        [80, 89]])

In [40]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [41]:
x = torch.tensor([2., 3., 4., 5.])
x

tensor([2., 3., 4., 5.])

In [43]:
x.norm()

tensor(7.3485)

In [44]:
x.numel()

4

In [45]:
len(a)

2

In [46]:
a.numel()

6