In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
type(x[1,1])

torch.Tensor

In [6]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [7]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x.view(2,5)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x.reshape(2,5)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x = x.view(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])